version: "3.9"

networks:
  private-network: {}

services:
  
  frontend:
    container_name: frontend
    image: arm64v8/nginx:1.23.2 # https://hub.docker.com/_/nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 8080:80
    networks:
      - private-network

  backend:
    container_name: backend
    image: arm64v8/node:18 # https://hub.docker.com/_/node
    working_dir: /usr/app
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: test
      DATABASE_PASSWORD: test
      DATABASE_NAME: test
    # command: npm start
    command: npm run dev
    volumes:
      - ./backend:/usr/app
    ports:
      - 3000:80
    networks:
      - private-network

  database:
    container_name: database
    image: arm64v8/mysql:latest # https://hub.docker.com/_/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./database/vol-1:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - private-network